### ISSUE TITLE
"inaktive Inhalte ansehen" does not work.

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.lawgiver#58]
The action group "view inactive objects" is translated as "inaktive Inhalte ansehen" (see https://github.com/4teamwork/ftw.lawgiver/blob/master/ftw/lawgiver/locales/de/LC_MESSAGES/ftw.lawgiver.po#L239).

Using "inaktive Inhalte ansehen" in a German specification file will throw a `Exception: Action "inaktive ansehen" is neither action group nor transition.` when generation the definition file.

**Comment by mbaechtold** [comment]
@jone, what do you think about changing the translation to "inaktive ansehen", this way one can use "inaktive Inhalte ansehen" in a German translation file?

**Comment by jone** [comment]
I think this is a problem in the [German parser](https://github.com/4teamwork/ftw.lawgiver/blob/master/ftw/lawgiver/wdl/languages/german.py#L82). 
:exclamation: But this actiongroup does not work and should not be used, see https://github.com/4teamwork/ftw.lawgiver/issues/27.
The problem is that those permissions are only relevant on the site root and not on any other object.

**Comment by mbaechtold** [comment]
Thank you @jone. Since this action should not be used this issue becomes obsolete and I'm closing it
